### ISSUE TITLE
Inbox selected tab text 

### ISSUE THREAD

**Issue by FadeMind** [CharlieEtienne/material-github#14]
IT IS
https://github.com/notifications/beta?query=is%3Aunread

![20200325-1585122539-001](https://user-images.githubusercontent.com/9846948/77513902-1ffb9880-6e76-11ea-8bea-8ab0d2e455e3.png)

SHOULD BE (I selected random darker color from picker for good apperance)
![20200325-1585122850-001](https://user-images.githubusercontent.com/9846948/77513953-37d31c80-6e76-11ea-85cd-b6b4d1fe6955.png)

CHROME CONSOLE with selectors. I made change in `.filter-item.selected, ul.filter-list .filter-item.selected,` for `color !important` direcly in chrome.

![20200325-1585122760-001](https://user-images.githubusercontent.com/9846948/77513972-3efa2a80-6e76-11ea-9022-dd7880cc331d.png)

please add this enhancement if you like. 

EDIT
Same is in sub menus
![20200325-1585123214-001](https://user-images.githubusercontent.com/9846948/77514424-20e0fa00-6e77-11ea-801b-e5ba800345fa.png)

**Comment by CharlieEtienne** [comment]
Hi, thanks for your suggestion, but I don't think I will implement that unfortunately.
I agree maybe with a darker background color for active menu to improve contrast, but I don't like the text color on links.
I'm trying to follow official material theme guidelines
