### ISSUE TITLE
developer.github.com articles unreadable

### ISSUE THREAD

**Issue by FabianLars** [CharlieEtienne/material-github#15]
for example:
[https://developer.github.com/webhooks/](https://developer.github.com/webhooks/)
or
[https://developer.github.com/changes/](https://developer.github.com/changes/)

Font and Background color is almost the same:
![image](https://user-images.githubusercontent.com/30730186/77658267-bca55f80-6f76-11ea-9850-2a800e43d2cb.png)

I hope this isn't just my color blindness kicking in lol

**Comment by CharlieEtienne** [comment]
Hi @FabianLars , no you're right 😄 !

I'll look into this in the weekend maybe, but PRs are welcome !

Cheers

**Comment by CharlieEtienne** [comment]
Hi @FabianLars, I think it's done (it might be imperfect, because the number of different pages and styles in developer part is huge)
