### ISSUE TITLE
Box-row Box-row--gray iin Recovery Option is not readable

### ISSUE THREAD

**Issue by FadeMind** [CharlieEtienne/material-github#20]
With enabled material github
`Box-row Box-row--gray` is white and strong field `Recovery Options` is not visible.

![20200416-1587047310-001](https://user-images.githubusercontent.com/9846948/79470269-7f763f80-8001-11ea-8826-25863fc4b5dd.png)
![20200416-1587047306-001](https://user-images.githubusercontent.com/9846948/79470284-81400300-8001-11ea-89b8-e3dbce90ebe8.png)

**Comment by CharlieEtienne** [comment]
Hide @FadeMind , thanks for reporting this. Where can I find this dropdown menu ? I can't find it and it would be easier for me to test it before committing.

**Comment by FadeMind** [comment]
>  Where can I find this dropdown menu?

https://github.com/settings/security

Two-factor authentication section

I deleted personal data setup here. 

![20200525-1590388942-001](https://user-images.githubusercontent.com/9846948/82785936-d58d9c80-9e63-11ea-8edd-c025a6ee4b29.png)
![20200525-1590388761-001](https://user-images.githubusercontent.com/9846948/82785939-d7576000-9e63-11ea-87cb-7a6882dc1758.png)

![20200525-1590389108-001](https://user-images.githubusercontent.com/9846948/82786083-3321e900-9e64-11ea-81ae-d25532de7ef4.png)

**Comment by legonigel** [comment]
githubs css for this is 
```css
.Box-row--gray {
    background-color: #f6f8fa;
}
```

**Comment by CharlieEtienne** [comment]
Thanks to both of you! I think it's fixed. I'm updated it right now on userstyles.org

Charlie
