### ISSUE TITLE
viewed checkbox on a PR is not properly styled

### ISSUE THREAD

**Issue by jnsn** [CharlieEtienne/material-github#25]
When unchecked, the `viewed` checkbox looks OK, but when it's selected the markup is barely readable.

![image](https://user-images.githubusercontent.com/348453/82728856-6729cc80-9cf3-11ea-9c41-addce24a8042.png)
![image](https://user-images.githubusercontent.com/348453/82728835-46617700-9cf3-11ea-92dc-dadbb8b9c1d6.png)

**Comment by CharlieEtienne** [comment]
Hi @jnsn , thanks for reporting this.

Todo:

- [ ] Add some fake checkboxes
- [x] Check one of them

**Comment by CharlieEtienne** [comment]
Oh sorry I thought you were speaking of comments checkboxes... Obviously not! 😃 
Do you have a link or some steps to follow to see this behaviour ?

Thanks,

Charlie

**Comment by jnsn** [comment]
Sure!

If you to the files tab of a PR, for example this one: https://github.com/CharlieEtienne/material-github/pull/17/files, there's a checkbox to the right of each file which you can toggle to collapse the file and mark it as _viewed_.

![image](https://user-images.githubusercontent.com/348453/82765450-76a23600-9e17-11ea-94da-a58b425bebfe.png)

**Comment by CharlieEtienne** [comment]
Thank you, and sorry for having misread, I just figured out that everything was in the title of your issue...

Anyway, it's fixed!
