### ISSUE TITLE
bg colours missing?

### ISSUE THREAD

**Issue by lf-** [CharlieEtienne/material-github#27]
Hi!

I installed this style from style.css in this repo and the background of most of the site was still white, making it effectively unusable since you can't read any of the light text on white.

It appears that the CSS declarations setting `--bg1`, `--bg2`, etc to whatever colour they are supposed to be are missing?

userstyles.org is falling over as seems to often be the case so I have not been able to tell if this issue reproduces on the version on there.

**Comment by lf-** [comment]
aha, it works when installed from userstyles.org. it finally installed. For the future though it would be good to have the colours available somewhere else for when userstyles.org dies.

**Comment by CharlieEtienne** [comment]
Hi @lf- , just so you know the css on github is not broken, it simply uses the userstyles.org system where you can choose from multiple theme (Oceanic, Darker, Palenight). These colors are located directly in userstyles.org

I simply put `/*[[theme]]*/` on the top of `style.css` and it can be automatically replaced with any content in userstyles.org. 

The content is related to the chosen theme:

# Oceanic theme

```css
--bg1: hsl(200, 19%, 13%);
--bg2: hsl(200, 19%, 15%);
--bg3: hsl(200, 19%, 18%);
--bg4: hsl(200, 19%, 20%);
--bg5: hsl(200, 19%, 24%);
--bg6: hsl(200, 19%, 27%);
```

# Darker theme

```css
--bg1: hsl(0, 0%, 13%);
--bg2: hsl(0, 0%, 15%);
--bg3: hsl(0, 0%, 18%);
--bg4: hsl(0, 0%, 20%);
--bg5: hsl(0, 0%, 24%);
--bg6: hsl(0, 0%, 27%);
```

# Palenight theme

```css
--bg1: hsl(229, 20%, 13%);
--bg2: hsl(229, 20%, 15%);
--bg3: hsl(229, 20%, 18%);
--bg4: hsl(229, 20%, 20%);
--bg5: hsl(229, 20%, 24%);
--bg6: hsl(229, 20%, 27%);
```

It's based on hue, saturation, and luminosity variations.

I will update the readme with more details for people like you who want to use it without userstyles.org

Thanks,

Charlie
