### ISSUE TITLE
GitHub version makes everything white; Userstyles version works properly

### ISSUE THREAD

**Issue by quantumgolem** [CharlieEtienne/material-github#31]
I'm not really sure why this is happening, but the GitHub version makes everything really white, although the Userstyles version makes everything look fine.

Userstyles:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24374968/85898420-3a714500-b7ca-11ea-9881-890b17c38762.png">

GitHub raw:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/24374968/85898430-3e9d6280-b7ca-11ea-91bc-eedbf23d20b0.png">

**Comment by CharlieEtienne** [comment]
Hi @sn0wyfall , did you follow the "**How To Install**" [here ](https://github.com/CharlieEtienne/material-github#how-to-use-it)?

**Comment by quantumgolem** [comment]
Hi! My bad, I'm actually using Cascadea (for Safari on macOS) to apply this. So I basically copied the source of the css and imported it into Cascadea. I see that this theme supposedly has settings, so maybe that's why it didn't work. 

Maybe I can import the theme in Stylish in Chrome, configure it, and then copy the CSS and paste it in Safari? Do you know where I could view the configured CSS? Would it be in the Stylish settings after configuring?

**Comment by CharlieEtienne** [comment]
You could copy the css in https://github.com/CharlieEtienne/material-github/blob/master/material-github.user.css from [line 53](https://github.com/CharlieEtienne/material-github/blob/master/material-github.user.css#L53) to the penultimate line (today [line 1022](https://github.com/CharlieEtienne/material-github/blob/master/material-github.user.css#L1022)) (you'll need to skip last `}` )

Then you'll need to replace `/*[[theme]]*/` with one of these:

- For "Oceanic" theme: `200, 19%`
- For "Darker" theme: `0, 0%`
- For "Palenight" theme: `229, 20%`

Or any values you like.

Then replace `/*[[lightness]]*/` with a value between `0.1` and `1.9` (default is `1`)

Then replace `/*[[accent]]*/` with one of these predefined accent values:

- "Turquoise": `174`
- "Tomato": `4`
- "Lavender": `262`
- "Daisy": `54`
- "Lime": `89`
- "Amethyst": `291`
- "Abyss": `229`
- "Orange": `15`
- "Oceanic": `199`
- "Acid lime": `73`
- "Dodgerblue": `218`
- "Strawberry": `340`
- "Light": `0`
- "Indigo": `231`
- "Water": `207`
- "Sky": `180`
- "Plant": `123`
- "Aquamarine": `166`
- "Cyan": `187`
- "Palenight": `231`
- "Amber": `51`
- "Atomic purple": `259`
- "Slate": `200`

Or a custom value of your choice

It should work fine but remember you won't be able to get theme updates and you'll need to update code manually.

**Comment by quantumgolem** [comment]
Wow, thanks a lot! This is super informative, useful, and cool! I'll do this!!
