### ISSUE TITLE
List separator request

### ISSUE THREAD

**Issue by Qwerty-Space** [CharlieEtienne/material-github#32]
Show separators between issues/files

**Comment by legonigel** [comment]
It appears that `.Box:not([style*="background"])` is setting the background to `--bg2` and `.Box-row` `border-top` is also set to `--bg2` so the separators are hidden. One of these probably needs to change color.

**Comment by CharlieEtienne** [comment]
Hi, I'm not sure where to find this problem... Could you post a screenshot maybe?

Thanks,

Charlie

**Comment by legonigel** [comment]
Sure. In any issues list there should be a border between the items in the list. 

Current:
![image](https://user-images.githubusercontent.com/2592586/86625097-5c608980-bf79-11ea-96c7-fee403938581.png)

With fixed `.Box-row` `border-top`:
![image](https://user-images.githubusercontent.com/2592586/86625187-8619b080-bf79-11ea-83fc-55fc57f2416c.png)

**Comment by CharlieEtienne** [comment]
Thank you, I understand now. 

I think in material design and material themes in general, most borders and separators tend to disappear. I don't personnaly think adding separators here would improve accessibility or clarity but I will let this issue open and if people vote for your request I will implement it.

Cheers,

Charlie

**Comment by CharlieEtienne** [comment]
I close this issue due to inactivity, feel free to reopen it if needed.
