### ISSUE TITLE
Project header white

### ISSUE THREAD

**Issue by legonigel** [CharlieEtienne/material-github#36]
Project headers are currently white:

![image](https://user-images.githubusercontent.com/2592586/86056392-3afc1c80-ba12-11ea-8361-3a3ceffece84.png)

Not sure where to add it, but the offending selector is `.project-header`

Example: 

https://github.com/grafana/grafana/projects/25#card-39005242

**Comment by ilharp** [comment]
Add the style below can fix it.

```css
.project-header {
    background-color: var(--bg1);
}
```

![image](https://user-images.githubusercontent.com/20179549/86120511-0453fe00-bb07-11ea-9c91-0c2d7adffc67.png)

+1 Not sure where to add it but I hope this problem can be fixed as soon as possible.

**Comment by CharlieEtienne** [comment]
Hi, as you can see GitHub has redesigned the UI. This one is fixed, but I have a lot of other things to fix to have a nice UI in the material colors. 
You can update and it should work. (Go to Stylus > Manage and update style)
