### ISSUE TITLE
Progress Bar foreground and background contrast

### ISSUE THREAD

**Issue by loquota** [CharlieEtienne/material-github#38]
**Selector**
`.task-progress .progress-bar .progress`

**Theme**
`Darker`

**Description**
The contrast between the foreground and background colors of the issue progress bars is very low. It's slightly visible at higher-than-default brightnesses by disappears at lower-than-default.

The progress bars for milestones and projects seems to use a bright green that might be more appropriate.

**Examples**

Issues:
![image](https://user-images.githubusercontent.com/67450103/86845362-9eb3c480-c066-11ea-927b-43ef39c03d55.png)

Milestones:
![image](https://user-images.githubusercontent.com/67450103/86845302-8774d700-c066-11ea-823d-cd2ac0c05622.png)

**Comment by CharlieEtienne** [comment]
Hi @loquota ,

Could you provide a link because I don't use Milestones and I can't find a repo using it to test some CSS improvements ?

Thank you,

Charlie

**Comment by loquota** [comment]
The kubernetes repo has both milestones and projects with visible progress bars, right now.

https://github.com/kubernetes/kubernetes/milestones
https://github.com/kubernetes/kubernetes/projects

**Comment by CharlieEtienne** [comment]
It's fixed, thanks @loquota
