### ISSUE TITLE
Style of PR toolbar

### ISSUE THREAD

**Issue by poly2d** [CharlieEtienne/material-github#4]
Hello! 👋 
Issue-ing another small style suggestion. 

<img width="789" alt="Screen Shot 2019-11-22 at 10 52 20 PM" src="https://user-images.githubusercontent.com/43548622/69474859-0c7eda80-0d7b-11ea-97bb-7a94d8aa7171.png">

I noticed that the toolbar found under  'Pull requests > Files changed' in a repo page does not have the theme colors. I did not notice it before, maybe it could be due to a recent Github css change.

Example: https://github.com/CharlieEtienne/material-github/pull/1/files

Thanks!

**Comment by CharlieEtienne** [comment]
Thank you @poly2d
