### ISSUE TITLE
SAML SSO text is white

### ISSUE THREAD

**Issue by AskAlice** [CharlieEtienne/material-github#44]
When authenticating my organization's login with github, the SSO auth text is white.

If you don't have an organization I imagine you might be able to replicate this if you attempt to authenticate an application with your github account.

I tried to request the stylesheet `sso.scss`  located at ` https://github.githubassets.com/app/app/assets/stylesheets/custom/github/sso.scss` but it gave me a 404. I also tried to access it in the sources and had the same issue. I presume it is a source map leaking from compiled css. Regardless, these should be pretty easy to override.

![image](https://user-images.githubusercontent.com/1855905/89787708-2adc6000-dadb-11ea-8120-492b29f00793.png)

```HTML
<div class="org-sso-panel">
    <div class="position-relative mt-2 mb-3">
      <img class="avatar mb-3" src="redacted" width="60" height="60" alt="">

      <h1 class="sso-title m-0">
        Single sign-on to
        <strong>My Org</strong>
      </h1>
    </div>


      <p class="text-gray-light mt-2 mb-4">
        Authenticate your account by logging into
        My Org’s
        single sign-on provider.
      </p>


    <!-- '"` --><!-- </textarea></xmp> --><form action="" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="">
      

      <button type="submit" class="btn btn-primary btn-block">Continue</button>
</form>  </div>
```
![image](https://user-images.githubusercontent.com/1855905/89788779-e81b8780-dadc-11ea-900f-edcbf3d56e58.png)
![image](https://user-images.githubusercontent.com/1855905/89788802-efdb2c00-dadc-11ea-8f89-4caf08ef6f5e.png)
![image](https://user-images.githubusercontent.com/1855905/89788842-fcf81b00-dadc-11ea-840c-bb996053468f.png)

**Comment by CharlieEtienne** [comment]
Hi @AskAlice, and thanks for reporting this.

 I added this code

```
.business-sso .business-sso-panel, .business-sso .org-sso-panel, .org-sso .business-sso-panel, .org-sso .org-sso-panel {
	background-color: var(--bg1) !important;
}
```

It should make background dark. 

You can update to last version.

Let me know if it doesn't work.

Cheers,

Charlie
