### ISSUE TITLE
Option to increase text lightness/contrast?

### ISSUE THREAD

**Issue by nyanpasu64** [CharlieEtienne/material-github#46]
Right now, Markdown/etc. body text is white with alpha 0.7. I find this color to be a bit darker than I prefer for comfortable reading. Is it possible to add an option to increase the brightness?

I suspect this won't be the easiest to override, since 0.7 appears in several rules which are `!important`. Writing my own userstyle to make text white will require tha I toggle Material Github and my own style simultaneously. And editing the style will break updates.

**Comment by CharlieEtienne** [comment]
Hi @nyanpasu64 , sure, I could add a setting to adjust text brightness. Let me dig into this. 
Another quick solution would be to decrease the "Custom theme lightness" setting ; it would result in having more contrast.

Cheers,

Charlie

**Comment by CharlieEtienne** [comment]
@nyanpasu64 I just added an option to increase (or decrease) text brightness. Could you update to v 3.3.0 and tell me if it is what you wanted ?

**Comment by nyanpasu64** [comment]
It seems to basically do what I want. Thanks!

I thought that with Firefox WebRender on, text with `color: rgba(alpha below 1)` would break subpixel antialiasing. However I haven't gotten issues on either WebRender or Chrome. So the current system should be working.

**Comment by CharlieEtienne** [comment]
Oh I didn't know it could cause that... Let me know if you see this kind of problem

**Comment by nyanpasu64** [comment]
If you want to look deeper into it:

https://github.com/servo/webrender/blob/master/webrender/doc/text-rendering.md

> To recap, here's what we gained and lost by making the transition from the full-component-alpha world to the regular rgba world: All colors and textures now only need four values to be represented, we still use a component alpha mask, and the results are equivalent to the full-component-alpha result assuming that the destination is opaque. We lost the ability to draw to partially transparent destinations.

I suggest you click on that link and scroll to the bottom. The equations are terrifyingly large ;)

My own testing on Firefox 81 WebRender and Chrome 85:

`<div style="color: rgba(1,1,1,0.5);">uwu</div>` is subpixel in Firefox and Chrome. So material-github is safe.

`<div style="opacity: 0.9;">uwu</div>` is grayscale in Chrome but subpixel in Firefox WebRender (and probably traditional rendering too).

Maybe WebRender was changed to no longer break subpixel rendering. I recall it used to. https://gankra.github.io/blah/text-hates-you/#subpixel-aa-isnt-composable talks about browsers incrementally trying to cripple subpixel.
