### ISSUE TITLE
the team page doesn't color completely

### ISSUE THREAD

**Issue by TUsama** [CharlieEtienne/material-github#47]
![image](https://user-images.githubusercontent.com/21279092/94354054-e6684c00-00a9-11eb-930b-73aabe846082.png)

the color of the team page seems not right, Is this a bug or something?

**Comment by CharlieEtienne** [comment]
Hi @TUsama ,

I don't use GitHub teams so I can't know the right css selector to add... Could you find the selector with white background for me ?

Thanks,

Charlie

**Comment by TUsama** [comment]
Sorry, Charlie, I don't have any program learning experience, what I can do is only to give you some information which may help you dig in this:

Charlie
![image](https://user-images.githubusercontent.com/21279092/94380168-fdb93f00-0166-11eb-9c5f-fc9defc81ead.png)

It's the picture of the corresponding part.

the code is here:

https://paste.ubuntu.com/p/qJZHMRPnpX/

I hope this can help you.

**Comment by FadeMind** [comment]
@CharlieEtienne  
![20201106-1604683704-001](https://user-images.githubusercontent.com/9846948/98396458-081c0200-205e-11eb-876f-f33b6a2ea88d.png)
![20201106-1604683629-001](https://user-images.githubusercontent.com/9846948/98396461-08b49880-205e-11eb-8ae2-65afdb1bce0a.png)

**Comment by CharlieEtienne** [comment]
@FadeMind do you mean I involuntarily fixed the team page?! 😄

**Comment by FadeMind** [comment]
@CharlieEtienne 

> I don't use GitHub teams so I can't know the right css selector

Now you get access 😁 (if @funilrys grant). 

EDIT: it is fixed partiarly.

**Comment by FadeMind** [comment]
@CharlieEtienne 

![20201106-1604694067-001](https://user-images.githubusercontent.com/9846948/98411368-37d70400-2076-11eb-9935-6ea9c7910e00.png)
![20201106-1604694023-001](https://user-images.githubusercontent.com/9846948/98411373-39083100-2076-11eb-880a-52756e4f6287.png)
![20201106-1604693960-001](https://user-images.githubusercontent.com/9846948/98411376-39083100-2076-11eb-96e1-462f29f25219.png)
```
class="member-suggestion-info"
```
```
.member-suggestion .member-suggestion-info {
    width: 90%;
    margin-top: 2px;
    margin-bottom: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
p {
    margin-top: 0;
    margin-bottom: 10px;
}
* {
    box-sizing: border-box;
}
user agent stylesheet
p {
    display: block;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
}
.typeahead-result.disabled {
    pointer-events: none;
    opacity: .5;
}
.typeahead-result {
    position: relative;
    display: block;
    min-width: 100%;
    padding: 10px;
    margin-top: 0;
    color: var(--color-text-primary);
    cursor: pointer;
}
user agent stylesheet
li {
    text-align: -webkit-match-parent;
}
.autocomplete-results {
    position: absolute;
    z-index: 99;
    width: 100%;
    max-height: 20em;
    overflow-y: auto;
    font-size: 13px;
    list-style: none;
    background: var(--color-bg-overlay);
    border: 1px solid var(--color-border-overlay);
    border-radius: 6px;
    box-shadow: var(--color-autocomplete-shadow);
}
user agent stylesheet
ul {
    list-style-type: disc;
}
body {
    word-wrap: break-word;
}
body {
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
    font-size: 14px;
    line-height: 1.5;
    color: var(--color-text-primary);
    background-color: var(--color-bg-canvas);
}
injected stylesheet
::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}
injected stylesheet
::-webkit-scrollbar-corner {
    background: none;
}
injected stylesheet
::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background: rgba(127, 127, 127, 0.6);
}
injected stylesheet
::-webkit-scrollbar-track {
    opacity: 0;
}
```

**Comment by CharlieEtienne** [comment]
oh that's nice I wasn't sure. Actually I have an GitHub organization and I just figured I could create a team inside. So I won't need to use yours. But that's very nice to you. 

I saw some color problems and I'm currently fixing them.

Thanks,

Charlie

**Comment by FadeMind** [comment]
@CharlieEtienne results strong ARE unreadable BLACK here. see code above your reply.

**Comment by CharlieEtienne** [comment]
I'm on it.

**Comment by FadeMind** [comment]
@CharlieEtienne Correction:
```
class="member-login"
```
CSS
```
element.style {
}
b, strong {
    font-weight: 600;
}
b, strong {
    font-weight: inherit;
    font-weight: bolder;
}
* {
    box-sizing: border-box;
}
user agent stylesheet
strong {
    font-weight: bold;
}
.member-suggestion .member-suggestion-info {
    width: 90%;
    margin-top: 2px;
    margin-bottom: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
.typeahead-result.disabled {
    pointer-events: none;
    opacity: .5;
}
.typeahead-result {
    position: relative;
    display: block;
    min-width: 100%;
    padding: 10px;
    margin-top: 0;
    color: var(--color-text-primary);
    cursor: pointer;
}
user agent stylesheet
li {
    text-align: -webkit-match-parent;
}
.autocomplete-results {
    position: absolute;
    z-index: 99;
    width: 100%;
    max-height: 20em;
    overflow-y: auto;
    font-size: 13px;
    list-style: none;
    background: var(--color-bg-overlay);
    border: 1px solid var(--color-border-overlay);
    border-radius: 6px;
    box-shadow: var(--color-autocomplete-shadow);
}
user agent stylesheet
ul {
    list-style-type: disc;
}
body {
    word-wrap: break-word;
}
body {
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
    font-size: 14px;
    line-height: 1.5;
    color: var(--color-text-primary);
    background-color: var(--color-bg-canvas);
}
injected stylesheet
::-webkit-scrollbar {
    width: 8px;
    height: 8px;
}
injected stylesheet
::-webkit-scrollbar-corner {
    background: none;
}
injected stylesheet
::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background: rgba(127, 127, 127, 0.6);
}
injected stylesheet
::-webkit-scrollbar-track {
    opacity: 0;
}

```

![20201106-1604694667-001](https://user-images.githubusercontent.com/9846948/98411991-699c9a80-2077-11eb-96e0-0fbe43fee1b5.png)

**Comment by FadeMind** [comment]
@CharlieEtienne GOT IT

![20201106-1604694853-001](https://user-images.githubusercontent.com/9846948/98412214-d879f380-2077-11eb-8987-d9ea3a9142b3.png)

```
.typeahead-result {
```
disabling
```
color: var(--color-text-primary);
```

**Comment by CharlieEtienne** [comment]
Should be fixed!

@FadeMind All you need here is to redefine `--color-text-primary` 😉

**Comment by FadeMind** [comment]
@CharlieEtienne nice blur
![20201106-1604695140-001](https://user-images.githubusercontent.com/9846948/98412607-8a192480-2078-11eb-8c0d-935baa8eddb8.png)

Thanks 🚀

**Comment by CharlieEtienne** [comment]
Mmh I should fix this white shadow...

**Comment by FadeMind** [comment]
> I should fix this white shadow

![20201106-1604695513-001](https://user-images.githubusercontent.com/9846948/98413121-64404f80-2079-11eb-8448-00e7552bc35c.png)
```
.autocomplete-results {
--color-autocomplete-shadow
```

@CharlieEtienne

**Comment by CharlieEtienne** [comment]
https://github.com/CharlieEtienne/material-github/commit/37767f410c7b686c62b466117ce709f027d5e8a5

**Comment by TUsama** [comment]
wow, thank you so much Charlie!

**Comment by funilrys** [comment]
My bad. Permission will be granted as soon as you accept it.
