### ISSUE TITLE
Editing PR diff-review comments

### ISSUE THREAD

**Issue by MV10** [CharlieEtienne/material-github#48]
Hello Charlie,

First I want to thank you -- this stylesheet is an eyeball-saver with large monitors! I really appreciate the effort you've put into it. (I personally hate CSS, so that makes me appreciate it even more! 😁 )

It seems there's an issue with editing PR diff-review comments. Notice the white border when editing, and the preview tab is completely whited out. This just started happening so I guess they changed something. As far as I can tell, this seems isolated to editing a previously posted comment, and only in the PR diff-review discussion area.

The edit tab:

![image](https://user-images.githubusercontent.com/794270/95655637-c9cf0980-0ad6-11eb-8a0d-1830289f54e8.png)

The preview tab:

![image](https://user-images.githubusercontent.com/794270/95655652-dbb0ac80-0ad6-11eb-8474-7b2e32144661.png)

**Comment by CharlieEtienne** [comment]
Thanks for the kind words! It should be fixed now, you can update
