### ISSUE TITLE
The title bar on each changed file is misaligned.

### ISSUE THREAD

**Issue by jim-barber-he** [CharlieEtienne/material-github#50]
It looks like GitHub changed something since this is a very recent issue.
I've updated to the latest Material Dark GitHub theme but unfortunately the problem persists.

With the Stylus theme disabled, the title-bars or headers (I don't know what to call them) for each file is properly aligned at the top:
![image](https://user-images.githubusercontent.com/38272327/97280746-a5658200-1877-11eb-8580-7aa43d80c3da.png)

But with the theme enabled, the title-bar has dropped and is obscuring the first 2 lines of code changes.
You can see the blank space above where it was supposed to be placed:
![image](https://user-images.githubusercontent.com/38272327/97280895-cded7c00-1877-11eb-9235-3d14716a6b05.png)

I only just noticed this today, so it broke in the past day or 2.

**Comment by CharlieEtienne** [comment]
Hi @jim-barber-he , unfortunately, I can't reproduce... Do you have a public link where I could see it in action ?

Thanks,

Charlie

**Comment by jim-barber-he** [comment]
I'm seeing it on this page for example:
https://github.com/aws/eks-charts/pull/286/files

I'm using Stylus in Firefox on Debian Linux (stable version).
Firefox was installed via the Debian package called firefox-esr at version 78.4.0esr-1~deb10u2

**Comment by CharlieEtienne** [comment]
@jim-barber-he It should be fixed now. I introduced this bug in a recent commit.

Thanks,

Charlie

**Comment by jim-barber-he** [comment]
Confirmed that it is fixed.
Thank you for such a useful theme.
