### ISSUE TITLE
GPG Verified sign unreadable, title border white. 

### ISSUE THREAD

**Issue by FadeMind** [CharlieEtienne/material-github#52]
Launch sample: `https://github.com/l1ving/youtube-dl/commit/c438ea87e4db650f5c44526b155ea335ea49d006` (coded against reference)

@CharlieEtienne  see
![20201029-1604004752-001](https://user-images.githubusercontent.com/9846948/97631345-1a2fec00-1a31-11eb-918c-24dc2f3d9740.png)
![20201029-1604004695-001](https://user-images.githubusercontent.com/9846948/97631346-1ac88280-1a31-11eb-9519-2d395aca065a.png)
![20201029-1604004679-001](https://user-images.githubusercontent.com/9846948/97631347-1ac88280-1a31-11eb-9f5f-6d0b6f62a010.png)

**Comment by CharlieEtienne** [comment]
Fixed! You can update @FadeMind 

Thanks for reporting this issue
