### ISSUE TITLE
Unreadable bold/italic markdown text when reviewing PRs

### ISSUE THREAD

**Issue by minhduc0711** [CharlieEtienne/material-github#53]
This happens in the "Files changed" tab of a Pull request page.
* Original
![image](https://user-images.githubusercontent.com/34294427/97652770-c73a5100-1a91-11eb-8fc2-e31fdf42b2f8.png)
* Material
![image](https://user-images.githubusercontent.com/34294427/97652672-88a49680-1a91-11eb-9478-483d6a029ac8.png)

**Comment by CharlieEtienne** [comment]
Should be fixed.

Thanks,

Charlie

**Comment by minhduc0711** [comment]
Thank you very much for the quick fix, but italic texts are still bad tho. The corresponding class would be `pl-mi` I think.

![image](https://user-images.githubusercontent.com/34294427/97690273-587be880-1acf-11eb-8e4c-7eb81e628131.png)

**Comment by CharlieEtienne** [comment]
whoops! should be good now. 

Thanks!
