### ISSUE TITLE
GitHub home page can not show properly

### ISSUE THREAD

**Issue by TUsama** [CharlieEtienne/material-github#55]
![image](https://user-images.githubusercontent.com/21279092/98338154-b2872b80-2044-11eb-936f-232892b819ed.png)

**Comment by FadeMind** [comment]
![20201106-1604652341-001](https://user-images.githubusercontent.com/9846948/98345718-5527b600-2015-11eb-9e27-46535e5beef7.png)

**Comment by CharlieEtienne** [comment]
It should be fixed. 

It seems that github is currently replacing some colors by vars, which is making theming more simple but also causes a lot of bugs in the theme these days. I do my best to keep it up to date.

Thanks,

Charlie
