### ISSUE TITLE
Organization sidebar isn't correctly styled

### ISSUE THREAD

**Issue by trossr32** [CharlieEtienne/material-github#56]
Currently when viewing an organization's settings the sidenav menu is incorrectly styled: 

![image](https://user-images.githubusercontent.com/332954/98375223-c0837f00-2039-11eb-8bb5-f5501f7c122c.png)

I have fixed this by duplicating .menu and .menu-item classes with .SideNav and .SideNav-item classes:

![image](https://user-images.githubusercontent.com/332954/98375479-0e988280-203a-11eb-8fcb-93e1052c7dcb.png)

Pull request incoming...

**Comment by trossr32** [comment]
See pull request #57

**Comment by CharlieEtienne** [comment]
Hi @trossr32, I fixed this issue 2 days ago in v3.3.18 (https://github.com/CharlieEtienne/material-github/commit/6455dab0344cf2706a8931f1e0894eff8d6a37b4). Did you update to the last version ?

**Comment by trossr32** [comment]
My apologies, I was on 3.3.17. I'll close this issue. 

Thanks for creating and maintaining this repo!
