### ISSUE TITLE
Official Dark

### ISSUE THREAD

**Issue by FadeMind** [CharlieEtienne/material-github#63]
@CharlieEtienne 
![20201209-1607513012-001](https://user-images.githubusercontent.com/9846948/101623923-72d3ab00-3a19-11eb-921a-7f14260eae9c.png)
![20201209-1607512990-001](https://user-images.githubusercontent.com/9846948/101623925-736c4180-3a19-11eb-8f24-c4df9d2d0c94.png)

**Comment by CharlieEtienne** [comment]
Haha, pretty neat! But it breaks some part of this theme... I will dive into it tonight.
